version: '3.6'

services:
  machine_learning_service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: machine_learning_image:v0.1
    container_name: machine_learning_container
    volumes:
      - /data:/data
      - ${WORKDIR}:/work
    ports:
      - "8889:8889" # jupyter lab
      - "6006:6006" # tensorboard
      - "6007:6007" # tensorboard
    command:
      - /bin/bash
    network_mode: host
    tty: true
    stdin_open: true

